services:
  andrewlynx.any_logger:
    class: 'Andrewlynx\Bundle\AnyLogger\AnyLogger'
    arguments:
      - '@service_container'

  Andrewlynx\Bundle\Controller\AnyLoggerController:
    public: true
    autoconfigure: true

  Andrewlynx\Bundle\Service\:
    resource: '../../Service'
    autowire: true
    autoconfigure: true

